version: '3'

services:
  zookeeper:
    container_name: go-producer-zookeeper
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"
  kafka:
    container_name: go-producer-kafka
    image: wurstmeister/kafka:0.11.0.0
    ports:
      - "9092:9092"
    environment:
          KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
